### ISSUE TITLE
gog.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#796] opened 2024-08-14 14:41 UTC
#### Browser
Firefox (129.0)
#### Reason
Cannot click
#### URL
https://www.gog.com/account/cloud-saves/page/1
#### Version
7.1.4

**Comment by cremor** [comment] 2024-08-14 14:42
1. On the linked site: Open a game with cloud saves from the list
2. Click the button "Remove old saves". Nothing happens.
3. Select one or more saves. Click the button "Delete selected files". Nothing happens.

The site works when Cookie Dialog Monster is disabled.

**Comment by wanhose** [comment] 2024-08-14 22:05
Hey @cremor,

I don't have any cloud saves. Once you've done those steps locally, would you mind saving the page as .html and sending that file to me through email to hello@wanhose.dev?

![image](https://github.com/user-attachments/assets/4d6bde86-bb0c-4a78-9d0b-af917c0a03b7)

![image](https://github.com/user-attachments/assets/7cd1fc40-7e9e-4d3f-a8f0-7bfbf9fdc612)

Let's see if I can help you. Thanks again!

**Comment by cremor** [comment] 2024-08-15 06:12
I can't reproduce the issue any more today.

After looking through the last commits it looks like this might have been fixed by https://github.com/wanhose/cookie-dialog-monster/commit/8a1b7ea4a09069996345a92d8b70eb9be0f65e84 (the revert for #758). Because I can also see a `cdk-overlay-container` element on that  gog.com site when the dialog is open.

**Closed** 2024-08-24 07:24 UTC
Labels: bug
